// src/graphics/vchundo-race/components/CompletionTable.vue
<template>
  <div :style="{ position: 'fixed' }">
    <table class="table table-bordered">
      <player-completion
        v-if="hundoTrackerData && hundoTrackerData.data"
        v-for="(player, i) in hundoTrackerData.data"
        :player="player"
        :position="i + 1"
        :key="player.name"
      />
    </table>
  </div>
</template>

<script setup lang="ts">
  import type { HundoTrackerData } from '@gtam-layouts/types/schemas';
  import { useReplicant } from 'nodecg-vue-composable';
  import PlayerCompletion from './CompletionTable/PlayerCompletion.vue';

  const hundoTrackerData = useReplicant<HundoTrackerData>(
    'hundoTrackerData',
    'gtam-layouts'
  );
</script>

// src/browser/graphics/components/vchundo-race/CompletionTable.tsx
import type { HundoTrackerData } from '@gtam-layouts/types'
import type { CSSProperties } from 'react'
import { useReplicant } from '@nodecg/react-hooks'
import { PlayerCompletion } from './CompletionTable/PlayerCompletion'

interface Props {
  style?: CSSProperties
}

export function CompletionTable({ style }: Props) {
  const [hundoTrackerData] = useReplicant<HundoTrackerData>('hundoTrackerData')

  return (
    <div style={{ position: 'fixed', ...style }}>
      <table className="table table-bordered">
        {hundoTrackerData && (
          <>
            {hundoTrackerData.map((player, i) => (
              <PlayerCompletion
                key={player.name}
                player={player}
                position={i + 1}
              />
            ))}
          </>
        )}
      </table>
    </div>
  )
}
