// src/browser/graphics/components/vchundo-race/Timer.tsx
import type { CSSProperties } from 'react'
import type { Timer as TimerType } from 'speedcontrol/types'
import { useReplicant } from '@nodecg/react-hooks'

interface Props {
  style?: CSSProperties
}

export function Timer({ style }: Props) {
  const [timer] = useReplicant<TimerType>('timer', { bundle: 'nodecg-speedcontrol' })

  return (
    <div
      className="Flex"
      style={{
        flexDirection: 'column',
        position: 'fixed',
        ...style,
      }}
    >
      <div
        id="Time"
        style={{
          fontSize: '2.3em',
          transition: '1s',
          marginBottom: '-0.2em',
        }}
      >
        {timer
        && (
          <span
            style={{
              display: 'inline-block',
              textAlign: 'center',
              color: '#a1ebff',
            }}
          >
            {timer.time}
          </span>
        )}
      </div>
    </div>
  )
}

// src/graphics/vchundo-race/components/Timer.vue
<template>
  <div class="Flex" :style="{ position: 'fixed' }">
    <div
      id="Time"
      :style="{
        'font-size': '2.3em',
        transition: '1s',
        'margin-bottom': '-0.2em',
      }"
    >
      <span v-if="timer && timer.data">
        {{ timer.data.time }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useReplicant } from 'nodecg-vue-composable';
  import { Timer } from 'speedcontrol/types';

  const timer = useReplicant<Timer>('timer', 'nodecg-speedcontrol');
</script>

<style scoped>
  .Flex {
    flex-direction: column;
  }

  /* Each character in the timer is in a span; setting width so the numbers appear monospaced. */
  #Time > span {
    display: inline-block;
    text-align: center;
    color: #a1ebff;
  }
</style>
