// src/dashboard/streamAssign/main.vue
<template>
  <v-app>
    <div v-if="enableChange">
      <div>
        <div v-if="!selectedRunner">
          <v-btn
            v-for="runner in runners"
            :key="runner.id"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(runner)"
          >
            {{ runner.name }}
          </v-btn>
        </div>
        <div v-else>
          <v-btn color="accent" disabled>
            {{ selectedRunner.name }}
          </v-btn>
        </div>
      </div>
      <div v-if="selectedRunner">
        <v-btn
          v-for="stream in streams"
          :key="stream"
          @click="assign(stream)"
          color="primary"
          :style="{
            'margin-top': '5px',
            'margin-right': '5px',
          }"
        >
          {{ stream.name }}
          <br />
          ({{ stream.twitchAccount }})
        </v-btn>
        <v-btn
          v-on:click="select(undefined)"
          color="secondary"
          :style="{
            'margin-top': '5px',
            'margin-right': '5px',
          }"
        >
          CANCEL
        </v-btn>
      </div>
    </div>
    <v-alert v-else dense type="info">
      Cannot change runners' feeds while the timer is running
    </v-alert>
  </v-app>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { State } from "vuex-class";
import {
  RunDataActiveRun,
  Timer,
} from "nodecg/bundles/nodecg-speedcontrol/src/types/schemas";

interface Player {
  name: string;
  id: string;
  teamID: string;
  country?: string;
  pronouns?: string;
  social: {
    twitch?: string;
  };
}

interface Stream {
  name: string;
  twitchAccount: string;
}

@Component
export default class App extends Vue {
  @State runDataActiveRun!: RunDataActiveRun;
  @State timer!: Timer;
  streams: Stream[] = nodecg.bundleConfig.feeds.streams;
  model = {
    selectedRunner: undefined,
  };

  get enableChange(): boolean {
    return !["running", "paused"].includes(this.timer.state);
  }

  get runners(): Player[] {
    var players = [];
    if (this.runDataActiveRun && this.runDataActiveRun.teams) {
      for (var team of this.runDataActiveRun.teams) {
        for (var player of team.players) {
          players.push(player);
        }
      }
    }
    return players;
  }
  get selectedRunner(): Player | undefined {
    return this.model.selectedRunner;
  }

  select(runner: Player): void {
    this.$set(this.model, "selectedRunner", runner);
  }

  assign(stream: Stream): void {
    var data = {
      runner: this.selectedRunner,
      stream: stream,
    };
    nodecg
      .sendMessage("assignStreamToRunner", data)
      .then(() => {})
      .catch(() => {});

    this.$set(this.model, "selectedRunner", undefined);
  }
}
</script>

// src/browser/dashboard/stream-assign.tsx
import type { Timer } from 'speedcontrol/types/schemas'
import { Alert, Button, Container } from '@mui/material'
import { useReplicant } from '@nodecg/react-hooks'
import { useEffect, useMemo, useState } from 'react'
import useCurrentRun from '../hooks/useCurrentRun'
import { render } from '../render'
import { DashboardThemeProvider } from './components/DashboardThemeProvider'

interface Player {
  name: string
  id: string
  teamID: string
  country?: string
  pronouns?: string
  social: {
    twitch?: string
  }
}

interface Stream {
  name: string
  twitchAccount: string
}

export function StreamAssign() {
  const [selectedPlayer, setSelectedPlayer] = useState<Player | null>(null)
  const [streams, setStreams] = useState<Stream[]>([])
  const currentRun = useCurrentRun()
  const [timer] = useReplicant<Timer>('timer', { bundle: 'nodecg-speedcontrol' })

  useEffect(() => {
    const configStreams = nodecg.bundleConfig.feeds.streams as Stream[]
    setStreams(configStreams)
  }, [])

  const runners = useMemo<Player[]>(() => {
    const players: Player[] = []
    if (currentRun && currentRun.teams) {
      for (const team of currentRun.teams) {
        for (const player of team.players) {
          players.push(player)
        }
      }
    }
    return players
  }, [currentRun])

  const enableChange = useMemo(() => timer && timer.state ? !['running', 'paused'].includes(timer.state) : false, [timer])

  const assign = (stream: Stream) => {
    nodecg.sendMessage('assignStreamToRunner', {
      runner: selectedPlayer?.name,
      stream,
    })

    setSelectedPlayer(null)
  }

  return (
    <DashboardThemeProvider>
      <Container>
        {enableChange
          ? (
              <Container>
                {!selectedPlayer
                  ? (runners.map(runner => (
                      <Button
                        variant="contained"
                        key={runner.id}
                        onClick={() => setSelectedPlayer(runner)}
                      >
                        {runner.name}
                      </Button>
                    )))
                  : (
                      <Button
                        variant="contained"
                        disabled
                      >
                        {selectedPlayer.name}
                      </Button>
                    )}
                {selectedPlayer && (
                  <Container>
                    {streams.map(stream => (
                      <Button
                        key={stream.name}
                        variant="contained"
                        onClick={() => assign(stream)}
                      >
                        {stream.name}
                        <br />
                        {stream.twitchAccount}
                      </Button>
                    ))}
                    <Button
                      variant="contained"
                      onClick={() => setSelectedPlayer(null)}
                    >
                      CANCEL
                    </Button>
                  </Container>
                )}
              </Container>
            )
          : (
              <Alert
                severity="info"
              >
                Cannot change runners' feeds while the timer is running
              </Alert>
            )}
      </Container>
    </DashboardThemeProvider>
  )
}

render(<StreamAssign />)
