// src/dashboard/vchundoselector/main.vue
<template>
  <v-app>
    <div>
      <div>
        <div v-if="!feedNumber">
          <v-btn
                    :disabled="model.feed1"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(1)"
          >
            Feed 1
          </v-btn>
          <v-btn
                              :disabled="model.feed2"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(2)"
          >
            Feed 2
          </v-btn>
          <v-btn
                              :disabled="model.feed3"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(3)"
          >
            Feed 3
          </v-btn>
          <v-btn
                              :disabled="model.feed4"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(4)"
          >
            Feed 4
          </v-btn>
          <v-btn
                              :disabled="model.feed5"
            :style="{ 'margin-right': '5px' }"
            v-on:click="select(5)"
          >
            Feed 5
          </v-btn>
        </div>
        <div v-else>
          <v-btn color="accent" disabled>
            Feed {{ feedNumber }}
          </v-btn>
        </div>
      </div>
      <div v-if="feedNumber">
        <v-btn
          v-for="runner in runners"
          :key="runner.id"
          @click="assign(runner)"
          color="primary"
          :style="{
            'margin-top': '5px',
            'margin-right': '5px',
          }"
        >
          {{ runner.players[0].name }}
        </v-btn>
      </div>

      <div>
        <v-btn
          :disabled="disableSend"
          :style="{             'margin-top': '5px',          'margin-right': '5px', }"
          v-on:click="send()"
        >
          SEND
        </v-btn>
        <v-btn
          :disabled="feedNumber"
          :style="{             'margin-top': '5px',          'margin-right': '5px', }"
          v-on:click="cancel()"
        >
          CANCEL
        </v-btn>
      </div>

    </div>
  </v-app>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { State } from "vuex-class";
import {  RunDataActiveRun } from "nodecg/bundles/nodecg-speedcontrol/src/types/schemas";
import { RunDataTeam } from "../../../../nodecg-speedcontrol/src/types";

@Component
export default class App extends Vue {
  @State runDataActiveRun!: RunDataActiveRun;
  model : {
    feedNumber: number | undefined,
    feed1: RunDataTeam | undefined,
    feed2: RunDataTeam | undefined,
    feed3: RunDataTeam | undefined,
    feed4: RunDataTeam | undefined,
    feed5: RunDataTeam | undefined,
  } = {
    feedNumber : undefined,
    feed1: undefined,
    feed2: undefined,
    feed3: undefined,
    feed4: undefined,
    feed5: undefined,
  };

  get runners(): RunDataTeam[] {
    return this.runDataActiveRun.teams.filter(team => team!=this.model.feed1 && team!=this.model.feed2 && team!=this.model.feed3 && team!=this.model.feed4 && team!=this.model.feed5);
  }
  get feedNumber(): number | undefined {
    return this.model.feedNumber;
  }
  get disableSend(): boolean{
    return this.feedNumber != undefined || this.model.feed1==undefined|| this.model.feed2==undefined|| this.model.feed3==undefined|| this.model.feed4==undefined|| this.model.feed5==undefined;
  }

  select(feedNumber: number): void {
    this.$set(this.model, "feedNumber", feedNumber);
  }

  assign(team: RunDataTeam): void {
    switch (this.model.feedNumber) {
      case 1:
        this.$set(this.model, "feed1", team);
        break;
      case 2:
        this.$set(this.model, "feed2", team);
        break;
      case 3:
        this.$set(this.model, "feed3", team);
        break;
      case 4:
        this.$set(this.model, "feed4", team);
        break;
      case 5:
        this.$set(this.model, "feed5", team);
        break;
      default:
    }

    this.$set(this.model, "feedNumber", undefined);
  }

  send():void{
    var data = {
      feed1: this.model.feed1,
      feed2: this.model.feed2,
      feed3: this.model.feed3,
      feed4: this.model.feed4,
      feed5: this.model.feed5,
    };
    nodecg
      .sendMessage("changeRunnersOnVCHundo", data)
      .then(() => {})
      .catch(() => {});

    this.$set(this.model, "feed1", undefined);
    this.$set(this.model, "feed2", undefined);
    this.$set(this.model, "feed3", undefined);
    this.$set(this.model, "feed4", undefined);
    this.$set(this.model, "feed5", undefined);
    this.$set(this.model, "selectedRunner", undefined);
  }
  
  cancel():void{
    this.$set(this.model, "feed1", undefined);
    this.$set(this.model, "feed2", undefined);
    this.$set(this.model, "feed3", undefined);
    this.$set(this.model, "feed4", undefined);
    this.$set(this.model, "feed5", undefined);
    this.$set(this.model, "selectedRunner", undefined);
  }
}
</script>

// src/browser/dashboard/vchundo-selector.tsx
import type { RunDataTeam } from 'speedcontrol/types'
import { Button, Container } from '@mui/material'
import { useMemo, useState } from 'react'
import useCurrentRun from '../hooks/useCurrentRun'
import { render } from '../render'
import { DashboardThemeProvider } from './components/DashboardThemeProvider'

interface Model {
  feedNumber: number | undefined
  feed1: RunDataTeam | undefined
  feed2: RunDataTeam | undefined
  feed3: RunDataTeam | undefined
  feed4: RunDataTeam | undefined
  feed5: RunDataTeam | undefined
}

export function VCHundoSelector() {
  const currentRun = useCurrentRun()

  const [model, setModel] = useState<Model>({
    feedNumber: undefined,
    feed1: undefined,
    feed2: undefined,
    feed3: undefined,
    feed4: undefined,
    feed5: undefined,
  })

  const availableRunners = useMemo(
    () =>
      (currentRun?.teams ?? []).filter(
        team =>
          team !== model.feed1
          && team !== model.feed2
          && team !== model.feed3
          && team !== model.feed4
          && team !== model.feed5,
      ),
    [currentRun, model],
  )

  const disableSend = useMemo(
    () =>
      model.feed1 === undefined
      || model.feed2 === undefined
      || model.feed3 === undefined
      || model.feed4 === undefined
      || model.feed5 === undefined,
    [model],
  )

  const assignRunner = (team: RunDataTeam) => {
    if (!model.feedNumber)
      return

    setModel(prev => ({
      ...prev,
      [`feed${prev.feedNumber}`]: team,
      feedNumber: undefined,
    }))
  }

  const selectFeed = (feedNumber: number) => {
    setModel(prev => ({ ...prev, feedNumber }))
  }

  const send = () => {
    const data = {
      feed1: model.feed1,
      feed2: model.feed2,
      feed3: model.feed3,
      feed4: model.feed4,
      feed5: model.feed5,
    }

    nodecg
      .sendMessage('changeRunnersOnVCHundo', data)
      .then(() => {})
      .catch(() => {})

    setModel({ ...model, feed1: undefined, feed2: undefined, feed3: undefined, feed4: undefined, feed5: undefined })
  }

  const cancel = () => {
    setModel({
      feedNumber: undefined,
      feed1: undefined,
      feed2: undefined,
      feed3: undefined,
      feed4: undefined,
      feed5: undefined,
    })
  }

  return (
    <DashboardThemeProvider>
      <Container>
        {!model.feedNumber
          ? (
              [1, 2, 3, 4, 5].map(num => (
                <Button
                  key={num}
                  disabled={model[`feed${num}` as keyof Model] !== undefined}
                  onClick={() => selectFeed(num)}
                  style={{ marginRight: '5px' }}
                >
                  Feed
                  {' '}
                  {num}
                </Button>
              ))
            )
          : (
              <Button variant="contained" disabled>
                Feed
                {model.feedNumber}
              </Button>
            )}
      </Container>
      <Container>
        {model.feedNumber && (
          <div>
            {availableRunners.map(runner => (
              <Button
                key={runner.id}
                onClick={() => assignRunner(runner)}
                style={{ marginTop: '5px', marginRight: '5px' }}
              >
                {runner.players[0]?.name}
              </Button>
            ))}
          </div>
        )}
      </Container>
      <Container>
        {' '}
        <Button
          disabled={disableSend}
          onClick={send}
          style={{ marginTop: '5px', marginRight: '5px' }}
        >
          SEND
        </Button>
        <Button
          disabled={model.feedNumber !== undefined}
          onClick={cancel}
          style={{ marginTop: '5px', marginRight: '5px' }}
        >
          CANCEL
        </Button>
      </Container>
    </DashboardThemeProvider>
  )
}

render(<VCHundoSelector />)
