// src/graphics/game-layout/components/Player.vue
<template>
  <div :style="{ position: 'fixed' }">
    <transition name="fade">
      <div
        v-if="name"
        :key="name"
        class="Flex"
        :style="{
          position: 'absolute',
          color: 'white',
          textShadow:
            '-2px -2px 0 #12222c, 0 -2px 0 #12222c, 2px -2px 0 #12222c, 6px 0 0 #12222c, 2px 2px 0 #12222c, 0 2px 0 #12222c, -2px 2px 0 #12222c, -2px 0 0 #12222c',
        }"
      >
        <div
          :style="{
            'margin-left': '5px',
          }"
          ref="player"
        >
          {{ name }}
          <span v-if="finishTime" :style="{ fontSize: '0.7em' }">
            [{{ finishTime }}]
          </span>
        </div>
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
  import { computed, watch } from 'vue';
  import { $ref } from 'vue/macros';
  import {
    RunDataActiveRun,
    Timer,
  } from 'nodecg/bundles/nodecg-speedcontrol/src/types';
  import { useReplicant } from 'nodecg-vue-composable';
  import fitty, { FittyInstance } from 'fitty';

  interface Props {
    size: number;
    team: number;
  }

  const props = withDefaults(defineProps<Props>(), {
    size: 64,
    team: 1,
  });

  const activeRun = useReplicant<RunDataActiveRun>(
    'runDataActiveRun',
    'nodecg-speedcontrol'
  );
  const timer = useReplicant<Timer>('timer', 'nodecg-speedcontrol');

  let timeout = 0;
  let teamI = 0;
  let index = 0;
  let name = $ref<string | null>(null);
  let playerFitty: FittyInstance | undefined = undefined;
  const player = $ref<HTMLDivElement | null>(null);

  const finishTime = computed<string | undefined>((): string | undefined => {
    if (activeRun && timer) {
      if (!activeRun.data || activeRun.data.teams.length <= 1) {
        return undefined;
      } else if (activeRun.data && timer.data) {
        const teamFinishTime =
          timer.data.teamFinishTimes[activeRun.data.teams[teamI].id];
        if (teamFinishTime) {
          if (teamFinishTime.state === 'completed') {
            return timer.data.teamFinishTimes[activeRun.data.teams[teamI].id]
              .time;
          } else if (teamFinishTime.state === 'forfeit') {
            return 'Forfeit';
          }
        }
      }
      return undefined;
    } else {
      return undefined;
    }
  });

  watch(
    () => activeRun?.data,
    (newValue) => {
      window.clearTimeout(timeout);
      teamI = props.team - 1;
      index = 0;
      name = null;
      const coop = !!(
        newValue &&
        newValue.teams.length === 1 &&
        newValue.teams[0].players.length >= 2
      );

      if (newValue) {
        if (coop && newValue.teams[0].players[teamI]) {
          name = newValue.teams[0].players[teamI].name;
        } else if (
          !coop &&
          newValue.teams[teamI] &&
          newValue.teams[teamI].players.length
        ) {
          showNextName();
        }
      }

      setTimeout(() => {
        if (player) {
          console.log('fitting');
          playerFitty = fitty(player, {
            maxSize: props.size,
            minSize: 24,
            multiLine: true,
          });
        }
      }, 200);
    },
    { immediate: true }
  );

  function showNextName(): void {
    if (activeRun) {
      if (!activeRun.data) {
        return;
      }
      const { players } = activeRun.data.teams[teamI];
      name = players[index].name;
      timeout = window.setTimeout(() => showNextName(), 30 * 1000);
      index = players.length <= index + 1 ? 0 : index + 1;
    }
  }
</script>

// src/browser/graphics/components/game-layouts/components/Player.tsx
import type { CSSProperties } from 'react'
import type { Timer } from 'speedcontrol/types'
import { useReplicant } from '@nodecg/react-hooks'
import { AutoTextSize } from 'auto-text-size'
import { useEffect, useMemo, useRef, useState } from 'react'
import useCurrentRun from '../../../../hooks/useCurrentRun'

interface Props {
  size: number
  team: number
  style?: CSSProperties
}

export function Player({ size = 64, team = 1, style }: Props) {
  const currentRun = useCurrentRun()
  const [timer] = useReplicant<Timer>('timer', { bundle: 'nodecg-speedcontrol' })

  const timeout = useRef(0)
  const teamI = useRef(0)
  const index = useRef(0)
  const [name, setName] = useState<string | null>(null)
  const nameRef = useRef(null)

  const showNextName = () => {
    if (currentRun && currentRun.teams[teamI.current]) {
      const team = currentRun.teams[teamI.current]

      setName(team?.players[index.current]?.name ?? '')
      timeout.current = window.setTimeout(() => showNextName(), 30 * 1000)
      index.current = (team?.players ?? []).length <= index.current + 1 ? 0 : index.current + 1
    }
  }

  useEffect(() => {
    window.clearTimeout(timeout.current)
    teamI.current = team - 1
    index.current = 0
    setName(null)
    const coop = !!(currentRun && currentRun.teams.length === 1 && currentRun.teams[0] && currentRun.teams[0].players.length >= 2)
    console.log(coop)
    if (coop && currentRun.teams[0] && currentRun.teams[0].players[teamI.current]) {
      setName(currentRun.teams[0].players[teamI.current]!.name)
    }
    else if (!coop && currentRun && currentRun.teams[0] && currentRun.teams[0].players[teamI.current]) {
      showNextName()
    }
  }, [currentRun])

  const finishTime = useMemo(() => {
    if (currentRun && timer) {
      if (currentRun.teams.length <= 1) {
        return undefined
      }
      else {
        const teamId = currentRun.teams[teamI.current]?.id
        if (teamId) {
          const teamFinishTime
                = timer.teamFinishTimes[teamId]
          if (teamFinishTime) {
            if (teamFinishTime.state === 'completed') {
              return timer.teamFinishTimes[teamId]?.time
            }
            else {
              return 'Forfeit'
            }
          }
          else {
            return undefined
          }
        }
        else {
          return undefined
        }
      }
    }
    else {
      return undefined
    }
  }, [timer, currentRun])

  return (
    <div style={{ position: 'fixed', ...style }} className="playerName">
      {name && (
        <div
          className="Flex"
          ref={nameRef}
          style={{
            position: 'absolute',
            color: 'white',
            textShadow:
                '-2px -2px 0 #12222c, 0 -2px 0 #12222c, 2px -2px 0 #12222c, 6px 0 0 #12222c, 2px 2px 0 #12222c, 0 2px 0 #12222c, -2px 2px 0 #12222c, -2px 0 0 #12222c',
          }}
        >
          <AutoTextSize maxFontSizePx={size} as="div" style={{ marginLeft: '5px' }}>
            {name}
            {finishTime && (
              <span style={{ fontSize: '0.7em' }}>
                [
                {finishTime}
                ]
              </span>
            )}
          </AutoTextSize>
        </div>
      )}
    </div>
  )
}
