// src/browser/graphics/components/game-layouts/components/Timer.tsx
import type { CSSProperties } from 'react'
import type { Timer as TimerType } from 'speedcontrol/types'
import { useReplicant } from '@nodecg/react-hooks'

interface Props {
  style?: CSSProperties
}

const timerColors = {
  stopped: '#a3a3a3',
  running: '#C736FF',
  paused: '#a304e2',
  finished: '#ffd557',
}

export function Timer({ style }: Props) {
  const [timer] = useReplicant<TimerType>('timer', { bundle: 'nodecg-speedcontrol' })

  return (
    <div
      className="Flex"
      style={{
        flexDirection: 'column',
        position: 'fixed',
        ...style,
      }}
    >
      {timer
      && (
        <div
          id="Timer"
          style={{
            fontSize: '2.8em',
            transition: 'color 1s',
            marginBottom: '-0.2em',
            color: timerColors[timer.state],
          }}
        >
          {timer.time.split('').map(char => (
            <span
              className={char === ':' ? 'Colon' : undefined}
              key={`${Math.random()}${char}`}
            >
              {char}
            </span>
          ))}

        </div>
      )}
    </div>
  )
}

// src/graphics/game-layout/components/Timer.vue
<template>
  <div class="Flex" :style="{ position: 'fixed' }">
    <div
      id="Time"
      v-if="timer && timer.data"
      :class="timer.data.state"
      :style="{
        'font-size': '2.8em',
        transition: '1s',
        'margin-bottom': '-0.2em',
      }"
    >
      <span
        v-for="char in timer.data.time.split('')"
        :key="`${Math.random()}${char}`"
        :class="char === ':' ? 'Colon' : undefined"
      >
        {{ char }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { Timer } from 'speedcontrol/types';
  import { useReplicant } from 'nodecg-vue-composable';

  const timer = useReplicant<Timer>('timer', 'nodecg-speedcontrol');
</script>

<style scoped>
  .Flex {
    flex-direction: column;
  }

  /* Each character in the timer is in a span; setting width so the numbers appear monospaced. */
  #Time > span,
  #Estimate > span {
    display: inline-block;
    width: 0.52em;
    text-align: center;
  }
  #Time > .Colon,
  #Estimate > .Colon {
    width: 0.3em;
  }

  .stopped {
    color: #a3a3a3;
  }
  .running {
    color: #C736FF;
  }
  .paused {
    color: #a304e2;
  }
  .finished {
    color: #ffd557;
  }
</style>
