// src/browser/graphics/components/game-layouts/16x9-3p.tsx
import L_Background from '../../img/game-layouts/16x9-3p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_16x9_3p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '1401px',
          top: '783px',
          width: '505px',
          height: '120px',
          fontSize: '40px',
        }}
      />
      <Estimate
        style={{
          left: '1401px',
          top: '883px',
          width: '505px',
          height: '100px',
          fontWeight: 'regular',
          fontSize: '30px',
        }}
      />
      <Game
        style={{
          left: '1401.5px',
          top: '565px',
          width: '505px',
          height: '200px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '1401.5px',
          top: '624px',
          width: '505px',
          height: '200px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '7.5px',
          top: '467px',
          width: '557px',
          height: '94px',
        }}
        size={52}
        team={1}
      />
      <Player
        style={{
          left: '1355.5px',
          top: '467px',
          width: '557px',
          height: '94px',
        }}
        size={52}
        team={2}
      />
      <Player
        style={{
          left: '775.5px',
          top: '467px',
          width: '370px',
          height: '92px',
        }}
        size={52}
        team={3}
      />
    </div>
  )
}

// src/graphics/game-layout/16x9-3p.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="./backgrounds/layoutbackground.png" />
      <img class="bg" src="./backgrounds/16x9-3p.png" />
    </div>
    <timer
      :style="{
        left: '1656px',
        top: '913px',
        width: '259px',
        height: '77px',
        fontSize: '26px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '1385px',
        top: '952px',
        width: '259px',
        height: '100px',
        fontWeight: 'regular',
        fontSize: '24px',
      }"
    ></estimate>
    <game
      :style="{
        left: '1080px',
        top: '828px',
        width: '330px',
        height: '58px',
        fontWeight: 'bold',
      }"
    ></game>
    <category
      :style="{
        left: '1605px',
        top: '827px',
        width: '300px',
        height: '54px',
        fontWeight: 'bold',
      }"
    ></category>
    <player
      :style="{
        left: '1000px',
        top: '40px',
        width: '300px',
        height: '100px',
      }"
      :size="46"
      :team="1"
    ></player>
    <player
      :style="{
        left: '1000px',
        top: '950px',
        width: '300px',
        height: '100px',
      }"
      :size="46"
      :team="2"
    ></player>
    <player
      :style="{
        left: '1540px',
        top: '160px',
        width: '300px',
        height: '100px',
      }"
      :size="46"
      :team="3"
    ></player>
  </div>
</template>

<script setup lang="ts">
  import Timer from './components/Timer.vue';
  import Estimate from './components/Estimate.vue';
  import Game from './components/Game.vue';
  import Category from './components/Category.vue';
  import Player from './components/Player.vue';
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>
