// src/browser/dashboard/layout-override.tsx
import type { GameLayouts } from '@gtam-layouts/types'
import type { ChangeEvent } from 'react'
import { FormControl, FormControlLabel, FormLabel, Radio, RadioGroup } from '@mui/material'
import { useReplicant } from '@nodecg/react-hooks'
import { useMemo } from 'react'
import { render } from '../render'
import { DashboardThemeProvider } from './components/DashboardThemeProvider'

export function LayoutOverride() {
  const [gameLayouts, setGameLayouts] = useReplicant<GameLayouts>('gameLayouts', { bundle: 'gtam-layouts' })

  const layoutOptions = useMemo(() => {
    if (gameLayouts && gameLayouts.available) {
      return gameLayouts.available.map((option) => {
        return {
          label: option.name,
          value: option.code,
        }
      })
    }
    else {
      return []
    }
  }, [gameLayouts])

  const handleRadioChange = (event: ChangeEvent<HTMLInputElement>) => {
    const newValue = (event.target as HTMLInputElement).value
    if (gameLayouts) {
      setGameLayouts({ ...gameLayouts, selected: newValue })
    }
  }

  return (
    <DashboardThemeProvider>
      <FormControl>
        <FormLabel>Select layout override</FormLabel>
        <RadioGroup value={gameLayouts?.selected} onChange={handleRadioChange}>
          {layoutOptions.map(option => (
            <FormControlLabel key={option.value} value={option.value} control={<Radio />} label={option.label} />
          ))}
        </RadioGroup>
      </FormControl>
    </DashboardThemeProvider>
  )
}

render(<LayoutOverride />)

// src/dashboard/layoutOverride/main.vue
<template>
  <div>
    <div class="q-pa-sm" v-if="gameLayouts && gameLayouts.data">
      <QOptionGroup
        v-model="gameLayouts.data!.selected"
        :options="layoutOptions"
        color="primary"
      />
      <QBtn
        color="black"
        label="Switch to selected layout"
        :disable="!gameLayouts.changed"
        @click="gameLayouts?.save"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
  import { useReplicant } from 'nodecg-vue-composable';
  import { GameLayouts } from '@gtam-layouts/types/schemas';
  import { computed } from 'vue';
  const gameLayouts = useReplicant<GameLayouts>('gameLayouts', 'gtam-layouts');

  const layoutOptions = computed(() => {
    if (gameLayouts && gameLayouts.data && gameLayouts.data.available) {
      return gameLayouts.data.available.map((option) => ({
        label: option.name,
        value: option.code,
      }));
    } else {
      return [];
    }
  });
</script>
