// src/graphics/16x9-bingo/main.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="../_misc/layoutbackground.png" />
      <img class="bg" src="./background.png" />
    </div>
    <timer
      :style="{
        left: '1693px',
        top: '537px',
        width: '259px',
        height: '75px',
        'font-size': '20px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '1525px',
        top: '530px',
        width: '259px',
        height: '75px',
        'font-weight': 'regular',
        'font-size': '20px',
      }"
    ></estimate>
    <game
      :style="{
        left: '1034px',
        top: '554px',
        width: '180px',
        height: '50px',
        fontWeight: 'bold',
      }"
      :size="40"
    ></game>
    <category
      :style="{
        left: '1380px',
        top: '553px',
        width: '195px',
        height: '52px',
        fontWeight: 'bold',
      }"
      :size="42"
    ></category>
    <player
      :style="{
        left: '968px',
        top: '1015px',
        width: '270px',
        height: '52px',
        fontWeight: 'bold',
      }"
      :size="40"
    ></player>
    <player
      :style="{
        left: '1300px',
        top: '1015px',
        width: '270px',
        height: '52px',
        fontWeight: 'bold',
      }"
      :size="40"
      :team="2"
    ></player>
    <player
      :style="{
        left: '1630px',
        top: '1015px',
        width: '270px',
        height: '52px',
        fontWeight: 'bold',
      }"
      :size="40"
      :team="3"
    ></player>
  </div>
</template>

<script setup lang="ts">
  import { useHead } from '@vueuse/head';
  import Timer from '../_misc/components/Timer.vue';
  import Estimate from '../_misc/components/Estimate.vue';
  import Game from '../_misc/components/Game.vue';
  import Category from '../_misc/components/Category.vue';
  import Player from '../_misc/components/Player.vue';

  useHead({ title: '16:9 Bingo' });
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/16x9-bingo.tsx
import L_Background from '../../img/game-layouts/16x9-bingo.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_16x9_Bingo() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '777px',
          top: '557px',
          width: '366px',
          height: '80px',
          fontSize: '32px',
        }}
      />
      <Estimate
        style={{
          left: '777px',
          top: '630px',
          width: '366px',
          height: '55px',
          fontWeight: 'regular',
          fontSize: '28px',
        }}
      />
      <Game
        style={{
          left: '798px',
          top: '246px',
          width: '326px',
          height: '65px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '798px',
          top: '320px',
          width: '326px',
          height: '50px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '0px',
          top: '412px',
          width: '768px',
          height: '107px',
        }}
        size={50}
        team={1}
      />
      <Player
        style={{
          left: '1152px',
          top: '412px',
          width: '768px',
          height: '107px',
        }}
        size={50}
        team={2}
      />
      <Player
        style={{
          left: '0px',
          top: '918px',
          width: '768px',
          height: '107px',
        }}
        size={50}
        team={3}
      />
    </div>
  )
}
