// src/graphics/16x9-1p/main.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="../_misc/layoutbackground.png" />
      <img class="bg" src="./background.png" />
    </div>
    <timer
      :style="{
        left: '1210px',
        top: '1000px',
        width: '208px',
        height: '77px',
        fontSize: '24px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '910px',
        top: '990px',
        width: '259px',
        height: '75px',
        fontWeight: 'regular',
        fontSize: '24px',
      }"
    ></estimate>
    <game
      :style="{
        left: '110px',
        top: '1022px',
        width: '345px',
        height: '50px',
      }"
      :size="40"
    ></game>
    <category
      :style="{
        left: '651px',
        top: '1020px',
        width: '290px',
        height: '50px',
        fontWeight: 'bold',
      }"
      :size="40"
    ></category>
    <player
      :style="{
        left: '1620px',
        top: '1020px',
        width: '285px',
        height: '50px',
      }"
      :size="40"
      :team="1"
    ></player>
  </div>
</template>

<script setup lang="ts">
  import { useHead } from '@vueuse/head';
  import Timer from '../_misc/components/Timer.vue';
  import Estimate from '../_misc/components/Estimate.vue';
  import Game from '../_misc/components/Game.vue';
  import Category from '../_misc/components/Category.vue';
  import Player from '../_misc/components/Player.vue';

  useHead({ title: '16:9 1 Player' });
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/16x9-1p.tsx
import L_Background from '../../img/game-layouts/16x9-1p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_16x9_1p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '1377px',
          top: '844px',
          width: '550px',
          height: '130px',
          fontSize: '30px',
        }}
      />
      <Estimate
        style={{
          left: '1377px',
          top: '930px',
          width: '550px',
          height: '80px',
          fontWeight: 'regular',
          fontSize: '26px',
        }}
      />
      <Game
        style={{
          left: '384px',
          top: '874px',
          width: '985px',
          height: '80px',
          fontWeight: 'bold',
        }}
        size={60}
      />
      <Category
        style={{
          left: '384px',
          top: '945px',
          width: '985px',
          height: '50px',
          fontWeight: 'bold',
        }}
        size={40}
      />
      <Player
        style={{
          left: '10px',
          top: '240px',
          width: '365px',
          height: '93px',
          fontWeight: 'bold',
        }}
        size={46}
        team={1}
      />
    </div>
  )
}
