// src/graphics/game-layout/16x9-2p.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="./backgrounds/16x9-2p.png" />
    </div>
    <timer
      :style="{
        left: '1285px',
        top: '730px',
        width: '635px',
        height: '150px',
        fontSize: '44px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '1285px',
        top: '865px',
        width: '635px',
        height: '74px',
        fontSize: '36px',
      }"
    ></estimate>
    <game
      :style="{
        left: '659px',
        top: '810px',
        width: '600px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="64"
    ></game>
    <category
      :style="{
        left: '652.5px',
        top: '860px',
        width: '615px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="35"
    ></category>
    <player
      :style="{
        left: '12.5px',
        top: '540px',
        width: '611px',
        height: '92px',
        fontSize: '24px',
      }"
      :size="54"
      :team="1"
    ></player>
    <player
      :style="{
        left: '1296.5px',
        top: '540px',
        width: '611px',
        height: '92px',
        fontSize: '24px',
      }"
      :size="54"
      :team="2"
    ></player>
  </div>
</template>

<script setup lang="ts">
  import Timer from './components/Timer.vue';
  import Estimate from './components/Estimate.vue';
  import Game from './components/Game.vue';
  import Category from './components/Category.vue';
  import Player from './components/Player.vue';
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/16x9-2p.tsx
import L_Background from '../../img/game-layouts/16x9-2p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_16x9_2p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '1285px',
          top: '685px',
          width: '635px',
          height: '150px',
          fontSize: '44px',
        }}
      />
      <Estimate
        style={{
          left: '1285px',
          top: '820px',
          width: '635px',
          height: '74px',
          fontSize: '36px',
        }}
      />
      <Game
        style={{
          left: '659px',
          top: '730px',
          width: '600px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '652.5px',
          top: '789px',
          width: '615px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '12.5px',
          top: '530px',
          width: '611px',
          height: '92px',
          fontSize: '24px',
        }}
        size={56}
        team={1}
      />
      <Player
        style={{
          left: '1296.5px',
          top: '530px',
          width: '611px',
          height: '92px',
          fontSize: '24px',
        }}
        size={56}
        team={2}
      />
    </div>
  )
}
