// src/graphics/game-layout/4x3-4p.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="./backgrounds/4x3-4p.png" />
    </div>
    <timer
      :style="{
        left: '745px',
        top: '527px',
        width: '426px',
        height: '100px',
        'font-size': '40px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '628px',
        top: '625px',
        width: '664px',
        height: '75px',
        'font-weight': 'regular',
        'font-size': '32px',
      }"
    ></estimate>
    <game
      :style="{
        left: '628px',
        top: '261px',
        width: '664px',
        height: '75px',
        fontWeight: 'bold',
      }"
      :size="72"
    ></game>
    <category
      :style="{
        left: '628px',
        top: '320px',
        width: '664px',
        height: '75px',
        fontWeight: 'bold',
      }"
      :size="44"
    ></category>
    <player
      :style="{
        left: '0px',
        top: '459px',
        width: '614px',
        height: '81px',
      }"
      :size="50"
      :team="1"
    ></player>
    <player
      :style="{
        left: '1306px',
        top: '459px',
        width: '614px',
        height: '81px',
      }"
      :size="50"
      :team="2"
    ></player>
    <player
      :style="{
        left: '0px',
        top: '999px',
        width: '614px',
        height: '81px',
      }"
      :size="50"
      :team="3"
    ></player>
    <player
      :style="{
        left: '1306px',
        top: '999px',
        width: '614px',
        height: '81px',
      }"
      :size="50"
      :team="4"
    ></player>
    <media-box
      :style="{
        left: '625.5px',
        bottom: '5px',
        width: '669px',
        height: '319px',
        fontSize: '30px',
      }"
    />
  </div>
</template>

<script setup lang="ts">
  import Timer from './components/Timer.vue';
  import Estimate from './components/Estimate.vue';
  import Game from './components/Game.vue';
  import Category from './components/Category.vue';
  import Player from './components/Player.vue';
  import MediaBox from './components/MediaBox.vue';
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/4x3-4p.tsx
import L_Background from '../../img/game-layouts/4x3-4p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { MediaBox } from './components/MediaBox'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_4x3_4p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '745px',
          top: '538px',
          width: '426px',
          height: '100px',
          fontSize: '40px',
        }}
      />
      <Estimate
        style={{
          left: '628px',
          top: '636px',
          width: '664px',
          height: '75px',
          fontWeight: 'regular',
          fontSize: '32px',
        }}
      />
      <Game
        style={{
          left: '643px',
          top: '331px',
          width: '634px',
          height: '75px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '643px',
          top: '390px',
          width: '634px',
          height: '75px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '0px',
          top: '458px',
          width: '614px',
          height: '81px',
          fontWeight: 'bold',
        }}
        size={25}
        team={1}
      />
      <Player
        style={{
          left: '1306px',
          top: '458px',
          width: '614px',
          height: '81px',
          fontWeight: 'bold',
        }}
        size={25}
        team={2}
      />
      <Player
        style={{
          left: '0px',
          top: '965px',
          width: '614px',
          height: '81px',
          fontWeight: 'bold',
        }}
        size={25}
        team={3}
      />
      <Player
        style={{
          left: '1306px',
          top: '965px',
          width: '614px',
          height: '81px',
          fontWeight: 'bold',
        }}
        size={25}
        team={4}
      />
      <MediaBox
        style={{
          left: '625.5px',
          bottom: '75px',
          width: '669px',
          height: '245px',
          fontSize: '30px',
        }}
      />
    </div>
  )
}
