// src/graphics/game-layout/4x3-2p.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="./backgrounds/4x3-2p.png" />
    </div>
    <timer
      :style="{
        left: '1285px',
        top: '815px',
        width: '635px',
        height: '150px',
        'font-size': '36px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '1285px',
        top: '935px',
        width: '635px',
        height: '75px',
        'font-weight': 'regular',
        'font-size': '30px',
      }"
    ></estimate>
    <game
      :style="{
        left: '659px',
        top: '884px',
        width: '600px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="72"
    ></game>
    <category
      :style="{
        left: '652.5px',
        top: '940px',
        width: '615px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="44"
    ></category>
    <player
      :style="{
        left: '12.5px',
        top: '720px',
        width: '610px',
        height: '85px',
        fontWeight: 'bold',
      }"
      :size="50"
      :team="1"
    ></player>
    <player
      :style="{
        left: '1297.5px',
        top: '720px',
        width: '610px',
        height: '85px',
        fontWeight: 'bold',
      }"
      :size="50"
      :team="2"
    ></player>
    <media-box
      :style="{
        left: '7.5px',
        bottom: '5px',
        width: '621px',
        height: '266px',
        fontSize: '30px',
      }"
    />
  </div>
</template>

<script setup lang="ts">
  import Timer from './components/Timer.vue';
  import Estimate from './components/Estimate.vue';
  import Game from './components/Game.vue';
  import Category from './components/Category.vue';
  import Player from './components/Player.vue';
  import MediaBox from './components/MediaBox.vue';
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/4x3-2p.tsx
import L_Background from '../../img/game-layouts/4x3-2p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { MediaBox } from './components/MediaBox'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_4x3_2p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '1285px',
          top: '796px',
          width: '635px',
          height: '150px',
          fontSize: '36px',
        }}
      />
      <Estimate
        style={{
          left: '1285px',
          top: '916px',
          width: '635px',
          height: '75px',
          fontWeight: 'regular',
          fontSize: '30px',
        }}
      />
      <Game
        style={{
          left: '659px',
          top: '852px',
          width: '600px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={60}
      />
      <Category
        style={{
          left: '652.5px',
          top: '900px',
          width: '615px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={40}
      />
      <Player
        style={{
          left: '12.5px',
          top: '723px',
          width: '610px',
          height: '85px',
          fontWeight: 'bold',
        }}
        size={50}
        team={1}
      />
      <Player
        style={{
          left: '1297.5px',
          top: '723px',
          width: '610px',
          height: '85px',
          fontWeight: 'bold',
        }}
        size={50}
        team={2}
      />
      <MediaBox
        style={{
          left: '7.5px',
          bottom: '75px',
          width: '621px',
          height: '226px',
          fontSize: '30px',
        }}
      />
    </div>
  )
}
