// src/graphics/game-layout/4x3-bingo.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="./backgrounds/4x3-bingo.png" />
    </div>
    <timer
      :style="{
        left: '140px',
        top: '972px',
        width: '259px',
        height: '75px',
        'font-size': '22px',
      }"
    ></timer>
    <estimate
      :style="{
        left: '-55px',
        top: '965px',
        width: '259px',
        height: '75px',
        'font-weight': 'regular',
        'font-size': '20px',
      }"
    ></estimate>
    <game
      :style="{
        left: '15px',
        top: '650px',
        width: '440px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="55"
    ></game>
    <category
      :style="{
        left: '15px',
        top: '815px',
        width: '440px',
        height: '100px',
        fontWeight: 'bold',
      }"
      :size="55"
    ></category>
    <player
      :style="{
        left: '20px',
        top: '490px',
        width: '320px',
        height: '80px',
        fontWeight: 'bold',
      }"
      :size="50"
      :team="1"
    ></player>
    <player
      :style="{
        left: '655px',
        top: '490px',
        width: '320px',
        height: '80px',
        fontWeight: 'bold',
      }"
      :size="50"
      :team="2"
    ></player>
    <player
      :style="{
        left: '1290px',
        top: '490px',
        width: '320px',
        height: '80px',
        fontWeight: 'bold',
      }"
      :size="50"
      :team="3"
    ></player>
  </div>
</template>

<script setup lang="ts">
  import Timer from './components/Timer.vue';
  import Estimate from './components/Estimate.vue';
  import Game from './components/Game.vue';
  import Category from './components/Category.vue';
  import Player from './components/Player.vue';
</script>

<style>
  @import url('../_misc/common.css');
  @import url('../_misc/Fade.css');
  @import url('../_misc/Flex.css');
</style>

// src/browser/graphics/components/game-layouts/4x3-bingo.tsx
import L_Background from '../../img/game-layouts/4x3-bingo.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_4x3_Bingo() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '745px',
          top: '537px',
          width: '426px',
          height: '100px',
          fontSize: '40px',
        }}
      />
      <Estimate
        style={{
          left: '628px',
          top: '635px',
          width: '664px',
          height: '75px',
          fontWeight: 'regular',
          fontSize: '32px',
        }}
      />
      <Game
        style={{
          left: '643px',
          top: '331px',
          width: '634px',
          height: '75px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '643px',
          top: '390px',
          width: '634px',
          height: '75px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '0px',
          top: '450px',
          width: '614px',
          height: '81px',
        }}
        size={36}
        team={1}
      />
      <Player
        style={{
          left: '1306px',
          top: '450px',
          width: '614px',
          height: '81px',
        }}
        size={36}
        team={2}
      />
      <Player
        style={{
          left: '0px',
          top: '958px',
          width: '614px',
          height: '81px',
        }}
        size={36}
        team={3}
      />
    </div>
  )
}
