// src/browser/graphics/components/game-layouts/4x3-2p.tsx
import L_Background from '../../img/game-layouts/4x3-2p.png'
import { Category } from './components/Category'
import { Estimate } from './components/Estimate'
import { Game } from './components/Game'
import { Player } from './components/Player'
import { Timer } from './components/Timer'
import '../../css/common.css'
import '../../css/Flex.css'
import '../../css/Fade.css'

export function L_4x3_2p() {
  return (
    <div>
      <div id="backgrounds">
        <img className="bg" src={L_Background} />
      </div>
      <Timer
        style={{
          left: '1285px',
          top: '785px',
          width: '635px',
          height: '150px',
          fontSize: '36px',
        }}
      />
      <Estimate
        style={{
          left: '1285px',
          top: '905px',
          width: '635px',
          height: '75px',
          fontWeight: 'regular',
          fontSize: '30px',
        }}
      />
      <Game
        style={{
          left: '659px',
          top: '824px',
          width: '600px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={72}
      />
      <Category
        style={{
          left: '652.5px',
          top: '890px',
          width: '615px',
          height: '100px',
          fontWeight: 'bold',
        }}
        size={44}
      />
      <Player
        style={{
          left: '12.5px',
          top: '703px',
          width: '610px',
          height: '85px',
          fontWeight: 'bold',
        }}
        size={56}
        team={1}
      />
      <Player
        style={{
          left: '1297.5px',
          top: '703px',
          width: '610px',
          height: '85px',
          fontWeight: 'bold',
        }}
        size={40}
        team={2}
      />
    </div>
  )
}

// src/graphics/4x3-2p/main.vue
<template>
  <div>
    <div id="backgrounds">
      <img class="bg" src="../_misc/layoutbackground.png" />
      <img class="bg" src="./background.png" />
    </div>
    <timer
      :style="{
        left: '950px',
        top: '913px',
        width: '259px',
        height: '75px',
        'font-size': '26px'
      }"
    ></timer>
    <estimate
      :style="{
        left: '680px',
        top: '960px',
        width: '259px',
        height: '75px',
        'font-weight': regular,
        'font-size': '22px'
      }"
    ></estimate>
    <game
      :style="{
        left: '500px',
        top: '770px',
        width: '450px',
        height: '100px',
        fontWeight: 'bold'
      }"
      :size="55"
    ></game>
    <category
      :style="{
        left: '975px',
        top: '770px',
        width: '450px',
        height: '100px',
        fontWeight: 'bold'
      }"
      :size="55"
    ></category>
    <player
      :style="{
        left: '30px',
        top: '770px',
        width: '450px',
        height: '100px',
        fontWeight: 'bold'
      }"
      :size="50"
    ></player>
    <player
      :style="{
        left: '1445px',
        top: '770px',
        width: '450px',
        height: '100px',
        fontWeight: 'bold'
      }"
      :size="50"
      :team="2"
    ></player>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
import { State } from "vuex-class";
import Timer from "../_misc/components/Timer.vue";
import Estimate from "../_misc/components/Estimate.vue";
import Game from "../_misc/components/Game.vue";
import Category from "../_misc/components/Category.vue";
import Player from "../_misc/components/Player.vue";
import { RunDataActiveRun } from "nodecg/bundles/nodecg-speedcontrol/src/types";

@Component({
  components: {
    Timer,
    Estimate,
    Game,
    Category,
    Player
  }
})
export default class App extends Vue {
  @State runDataActiveRun!: RunDataActiveRun;
}
</script>

<style>
@import url("../_misc/common.css");
@import url("../_misc/Fade.css");
@import url("../_misc/Flex.css");
</style>
