// src/graphics/omnibar/components/Ticker/NextRun.vue
<template>
  <div id="NextRun" :style="{ fontSize: '40px' }" v-html="msg"></div>
</template>

<script setup lang="ts">
  import { onMounted } from 'vue';
  import { $ref } from 'vue/macros';
  import {
    RunData,
    RunDataActiveRun,
    RunDataArray,
  } from 'speedcontrol/types';
  import { timeToRun } from '../../../_misc/time-to-run';
  import { formatPlayers } from '../../../_misc/format-players';
  const activeRun = nodecg.Replicant<RunDataActiveRun>(
    'runDataActiveRun',
    'nodecg-speedcontrol'
  );
  const runDataArray = nodecg.Replicant<RunDataArray>(
    'runDataArray',
    'nodecg-speedcontrol'
  );

  const emit = defineEmits(['end']);

  let msg = $ref('');

  function getNextRun(): RunData | null {
    if (runDataArray.value && activeRun.value) {
      const activeRunId = activeRun.value.id;
      if (activeRunId) {
        const activeRunIndex = runDataArray.value.findIndex(
          (run) => run.id === activeRunId
        );
        return runDataArray.value[activeRunIndex + 1];
      } else {
        return null;
      }
    } else {
      return null;
    }
  }

  onMounted(() => {
    setTimeout(() => {
      const nextRun = getNextRun();
      if (nextRun) {
        msg = `Next run in <span class="highlight">${timeToRun(
          nextRun
        )}</span> - ${nextRun.customData['gameShort'] || nextRun.game} ${
          nextRun.category
        } by <span class="highlight">${formatPlayers(nextRun)}</span>`;
      } else {
        emit('end');
      }
    }, 200);

    console.log('NextRun: Mounted');
    setTimeout(() => {
      emit('end');
      console.log('NextRun: ended');
    }, 20 * 1000);
  });
</script>

// src/browser/graphics/components/omnibar/Ticker/NextRun.tsx
import type { RunData } from 'speedcontrol/types'
import type { RunDataActiveRunSurrounding } from 'speedcontrol/types/schemas'
import { useLayoutEffect, useState } from 'react'
import { Helpers } from '../../../../helpers'

const runDataArray = nodecg.Replicant<RunData[]>(
  'runDataArray',
  'nodecg-speedcontrol',
)
const runDataActiveRunSurrounding = nodecg.Replicant <RunDataActiveRunSurrounding>(
  'runDataActiveRunSurrounding',
  'nodecg-speedcontrol',
)

function getNextRun() {
  return (runDataArray.value ?? []).find(run => run.id === runDataActiveRunSurrounding.value?.next)
}

interface Props {
  time: number
  onEnd: () => void
}

export function NextRun({ time, onEnd }: Props) {
  const [msg, setMsg] = useState('')

  useLayoutEffect(() => {
    console.log('NextRun: Mounted')

    NodeCG.waitForReplicants(runDataArray, runDataActiveRunSurrounding).then(() => {
      const nextRun = getNextRun()
      if (nextRun) {
        const timeToRun = Helpers.timeToRun(nextRun)
        if (timeToRun.length > 0) {
          setMsg(
            `Next run in <span class="highlight">${timeToRun}</span> - ${nextRun.customData['gameShort'] ?? nextRun.game} ${nextRun.category} by <span class="highlight">${Helpers.formatPlayers(nextRun)}</span>`,
          )
        }
        else {
          setMsg(
            `Next run - ${nextRun.customData['gameShort'] ?? nextRun.game} ${nextRun.category} by <span class="highlight">${Helpers.formatPlayers(nextRun)}</span>`,
          )
        }
      }
      else {
        console.log('NextRun: End')
        onEnd()
      }
    })

    const exitTimeout = setTimeout(() => {
      console.log('NextRun: End')
      onEnd()
    }, time * 1000)

    return () => {
      clearTimeout(exitTimeout)
    }
  }, [])

  return (
    <div
      id="NextRun"
      style={{ fontSize: '40px' }}
      dangerouslySetInnerHTML={{ __html: msg }}
    />
  )
}
