// src/graphics/intermission/components/UpcomingRun.vue
<template>
  <div :style="{ position: 'fixed' }">
    <transition name="fade" mode="out-in" appear>
      <div v-if="!run" class="Flex" :style="{ 'font-size': '3em' }"></div>
      <div
        v-else
        :key="run.id"
        class="Flex"
        :style="{
          'padding-left': '15px',
          'padding-right': '15px',
          'font-size': bigFontSize + 'px',
          width: bigWidth + 'px',
        }"
      >
        <div
          :style="{
            'flex-direction': 'column',
            'text-align': 'left',
            'align-items': 'normal',
          }"
        >
          <div
            id="game"
            ref="game"
            :style="{
              'font-size': '1em',
              width: bigWidth + 'px',
              marginBottom: '-5px',
            }"
          >
            {{ run.game }}
          </div>
          <div
            id="category"
            ref="category"
            :style="{
              'font-size': catRatio + 'em',
              width: bigWidth + 'px',
              /* color: '#4fbafe', */
            }"
          >
            {{ run.category }}
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
  import { onMounted, ref, watch } from 'vue';
  import { RunData } from 'nodecg/bundles/nodecg-speedcontrol/src/types';
  import fitty, { FittyInstance } from 'fitty';

  interface Props {
    run: RunData | null;
  }

  const props = withDefaults(defineProps<Props>(), {
    run: null,
  });

  const game = ref<HTMLDivElement | null>(null);
  const category = ref<HTMLDivElement | null>(null);
  let bigFontSize = 48;
  let bigWidth = 872;
  let catRatio = 0.75;
  let minSizeRatio = 0.4;
  let gameFitty: FittyInstance | undefined = undefined;
  let categoryFitty: FittyInstance | undefined = undefined;

  function fit() {
    if (game.value) {
      gameFitty = fitty(game.value, {
        maxSize: bigFontSize,
        minSize: bigFontSize * minSizeRatio,
        multiLine: false,
      });
    }
    if (category.value) {
      categoryFitty = fitty(category.value, {
        maxSize: bigFontSize * catRatio,
        minSize: bigFontSize * minSizeRatio * catRatio,
        multiLine: false,
      });
    }
  }

  onMounted(() => {
    setTimeout(() => {
      fit();
    }, 550);
  });

  watch(
    () => props.run,
    () => {
      setTimeout(() => {
        fit();
      }, 550);
    }
  );
</script>

<style scoped>
  .Flex {
    flex-direction: column;
    text-align: left;
    align-items: normal;
  }
</style>

// src/browser/graphics/components/intermission/UpcomingRun.tsx
import type { CSSProperties } from 'react'
import type { RunData } from 'speedcontrol/types'
import { AutoTextSize } from 'auto-text-size'
import { useRef } from 'react'
import { CSSTransition, SwitchTransition } from 'react-transition-group'

interface Props {
  run: RunData
  style: CSSProperties
}

export function UpcomingRun({ run, style }: Props) {
  const bigFontSize = 48
  const bigWidth = 872
  const catRatio = 0.75
  const minSizeRatio = 0.4

  const runComponentRef = useRef(null)

  return (
    <div style={{ position: 'fixed', ...style }}>
      <SwitchTransition mode="out-in">
        <CSSTransition
          key={run.id}
          nodeRef={runComponentRef}
          in
          appear
          timeout={1000}
          classNames="fade"
        >
          <div
            key={run.id}
            ref={runComponentRef}
            className="Flex"
            style={{
              paddingLeft: '15px',
              paddingRight: '15px',
              width: `${bigWidth}px`,
            }}
          >
            <div
              style={{
                flexDirection: 'column',
                textAlign: 'left',
                alignItems: 'normal',
              }}
            >
              <AutoTextSize
                id="game"
                as="div"
                minFontSizePx={bigFontSize * minSizeRatio}
                maxFontSizePx={bigFontSize}
                mode="boxoneline"
                style={{
                  width: `${bigWidth}px`,
                  marginBottom: '-5px',
                }}
              >
                {run.game}
              </AutoTextSize>
              <AutoTextSize
                id="category"
                as="div"
                minFontSizePx={bigFontSize * minSizeRatio * catRatio}
                maxFontSizePx={bigFontSize * catRatio}
                mode="boxoneline"
                style={{
                  width: `${bigWidth}px`,
                  marginBottom: '-5px',
                }}
              >
                {run.category}
              </AutoTextSize>
            </div>
          </div>
        </CSSTransition>
      </SwitchTransition>
    </div>
  )
}
