// src/browser/graphics/components/game-layouts/components/MediaBox/Image.tsx
import type { MediaBoxImages } from '@gtam-layouts/types'
import { useMemo } from 'react'

interface Props {
  images: MediaBoxImages
  useWidescreenImages: boolean
}

export function MediaBoxImage({ images, useWidescreenImages }: Props) {
  const image = useMemo(() => {
    return useWidescreenImages ? images.widescreen : images.standard
  }, [images, useWidescreenImages])
  return (
    <div
      id="MediaBoxImage"
      className="Flex"
      style={{
        width: '100%',
        height: '100%',
        objectFit: 'contain',
        verticalAlign: 'middle',
        alignItems: 'center',
        alignContent: 'center',
        margin: 'auto',
      }}
    >
      {image && image.name && (
        <img
          key={image.name}
          src={image.url}
          style={{
            maxWidth: '100%',
            maxHeight: '100%',
            width: 'auto',
            height: 'auto',
          }}
        />
      )}
    </div>
  )
}

// src/graphics/game-layout/components/MediaBox/Image.vue
<template>
  <div id="MediaBoxImage" class="Flex">
    <img v-if="image && image.name" :key="image.name" :src="image.url" />
  </div>
</template>

<script setup lang="ts">
  import { defineProps } from 'vue';
  import { $ref } from 'vue/macros';
  const props = defineProps({
    image: {
      type: Object,
      required: true,
    },
    useWidescreen: {
      type: Boolean,
    },
  });
  const image = $ref(
    props.useWidescreen ? props.image.widescreen : props.image.standard
  );
</script>

<style scoped>
  #MediaBoxImage {
    width: 100%;
    height: 100%;
    object-fit: contain;
    vertical-align: middle;
    align-items: center;
    align-content: center;
    margin: auto;
  }

  img {
    max-width: 100%;
    max-height: 100%;
    width: auto;
    height: auto;
  }
</style>
