// src/browser/graphics/components/game-layouts/components/MediaBox/MerchAlert.tsx
import type { MerchItem, MerchQueueItem } from '@gtam-layouts/types'
import { useEffect, useRef, useState } from 'react'
import { CSSTransition, SwitchTransition } from 'react-transition-group'
import styles from '../../../../css/components/MerchAlert.module.css'

interface Props {
  merchInfo: MerchQueueItem
}

export function MediaBoxMerchAlert({ merchInfo }: Props) {
  const { name, items } = merchInfo

  const [currentItem, setCurrentItem] = useState<MerchItem | undefined>(
    items.length > 0 && items[0] ? items[0] : undefined,
  )
  const [currentIndex, setCurrentIndex] = useState(0)
  const merchContainerRef = useRef(null)

  useEffect(() => {
    if (!items.length)
      return

    setCurrentItem(items[currentIndex])

    const timeout = setTimeout(() => {
      if (!(currentIndex + 1 >= items.length)) {
        setCurrentIndex(prev => prev++)
      }
    }, 20000 / items.length)

    return () => clearTimeout(timeout)
  }, [currentIndex, items])

  const getItemImage = (item: string): string => {
    try {
      return new URL(`./merch/${item}.png`, import.meta.url).href
    }
    catch {
      return new URL('./emotes/gtaPOGGERS.png', import.meta.url).href
    }
  }

  return (
    <>
      {merchInfo && currentItem && (
        <div id="MediaBoxMerchAlert" style={{ width: '100%', height: '100%' }}>
          <SwitchTransition mode="out-in">
            <CSSTransition
              key={currentItem.name}
              nodeRef={merchContainerRef}
              in
              appear
              timeout={1000}
              classNames="fade"
            >
              <div
                style={{ textShadow: '2px 2px 2px #12222c', gap: '20px' }}
                className={styles['Flex']}
                ref={merchContainerRef}
              >
                <img src={getItemImage(currentItem.name)} />
                <span>
                  <b className={styles['highlight']}>{name}</b>
                  has bought
                  <b className={styles['highlight']}>
                    {currentItem.quantity}
                    x
                    &nbsp;
                    {currentItem.name}
                  </b>
                  !
                </span>
              </div>
            </CSSTransition>
          </SwitchTransition>
        </div>
      )}
    </>
  )
}

// src/graphics/game-layout/components/MediaBox/MerchAlert.vue
<template>
  <div id="MediaBoxMerchAlert" v-if="data && data.merchInfo && currentItem">
    <transition name="fade" mode="out-in">
      <div
        :style="{
          textShadow: '2px 2px 2px #12222c',
          gap: '20px',
        }"
        class="Flex"
        :key="currentItem.name"
      >
        <img :src="getItemImage(currentItem.name)" />
        <span>
          <b class="highlight">{{ data.merchInfo.name }}</b> has bought
          <b class="highlight"
            >{{ currentItem.quantity }}x {{ currentItem.name }}</b
          >!
        </span>
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
  import type { MerchQueueItem } from '@gtam-layouts/types';
  import { MerchItem } from '@gtam-layouts/types/seEvents';
  import { defineProps, defineEmits, watch } from 'vue';
  import { $ref } from 'vue/macros';

  const props = defineProps<{
    data: { merchInfo: MerchQueueItem | undefined };
  }>();
  const emit = defineEmits(['merchEnd', 'end']);
  let currentItem = $ref<MerchItem | null>(null);
  let index = 0;
  let timeout: NodeJS.Timeout;

  function getItemImage(item: string): string {
    const url = new URL(`./merch/${item}.png`, import.meta.url).href;
    if (!url.endsWith('undefined')) {
      return url;
    } else {
      return new URL('./emotes/gtaPOGGERS.png', import.meta.url).href;
    }
  }

  function setNextItem() {
    index++;
    clearTimeout(timeout);
    if (index >= props.data.merchInfo!.items.length) {
      emit('merchEnd');
    }
    currentItem = props.data.merchInfo!.items[index];
    timeout = setTimeout(() => {
      setNextItem();
    }, 25000 / props.data.merchInfo!.items.length);
  }

  watch(
    () => {
      props.data.merchInfo;
    },
    () => {
      if (props.data.merchInfo && props.data.merchInfo.items.length) {
        currentItem = props.data.merchInfo.items[index];
        timeout = setTimeout(() => {
          setNextItem();
        }, 25000 / props.data.merchInfo.items.length);
      } else {
        emit('end');
      }
    },
    { immediate: true }
  );
</script>

<style scoped>
  .highlight {
    color: #4fbafe;
  }

  .Flex {
    position: absolute;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 100%;
    overflow: hidden;
    text-align: center;
  }
</style>
