// src/graphics/omnibar/components/Ticker.vue
<template>
  <div
    id="Ticker"
    :style="{
      overflow: 'hidden',
      flex: 1,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    }"
  >
    <transition
      enter-active-class="animate__animated animate__slideInDown"
      leave-active-class="animate__animated animate__slideOutDown"
      mode="out-in"
      ><component
        :is="currentComponent.name"
        :key="timestamp"
        :data="currentComponent.data"
        @end="showNextMsg"
    /></transition>
  </div>
</template>

<script setup lang="ts">
  import { $ref } from 'vue/macros';
  import GenericMessage from './Ticker/GenericMessage.vue';
  import NextRun from './Ticker/NextRun.vue';
  import { onMounted } from 'vue';
  import { Configschema } from '@gtam-layouts/types/schemas';
  import {
    RunDataActiveRun,
    RunDataArray,
  } from 'speedcontrol/types';

  const runs = nodecg.Replicant<RunDataArray>(
    'runDataArray',
    'nodecg-speedcontrol'
  );
  const activeRun = nodecg.Replicant<RunDataActiveRun>(
    'runDataActiveRun',
    'nodecg-speedcontrol'
  );
  const currentOBSScene = nodecg.Replicant<string>('currentOBSScene');
  const intermission = (nodecg.bundleConfig as Configschema).obs.names.scenes
    .intermission;

  let currentComponent = $ref<{ name: any; data: Object }>({
    name: '',
    data: {},
  });
  let currentComponentIndex = 0;
  let timestamp = $ref(Date.now());
  let messageTypes: any[] = [];
  let intermissionMessageTypes: any[] = [];

  onMounted(() => {
    NodeCG.waitForReplicants(runs, activeRun, currentOBSScene).then(() => {
      messageTypes = [gtuPromo(), merchPromo(), schedulePromo(), nextRun()];
      intermissionMessageTypes = [gtuPromo(), merchPromo(), schedulePromo()];
      currentComponent = messageTypes[0];
    });
  });

  function showNextMsg() {
    console.log('SHOWING NEXT MESSAGE');
    if (currentOBSScene.value != intermission) {
      currentComponentIndex += 1;
      if (currentComponentIndex >= messageTypes.length) {
        currentComponentIndex = 0;
      }
      currentComponent = messageTypes[currentComponentIndex];
    } else {
      currentComponentIndex += 1;
      if (currentComponentIndex >= intermissionMessageTypes.length) {
        currentComponentIndex = 0;
      }
      currentComponent = intermissionMessageTypes[currentComponentIndex];
    }

    timestamp = Date.now();
  }

  function genericMsg(msg: string) {
    return {
      name: GenericMessage,
      data: {
        msg,
      },
    };
  }

  function gtuPromo() {
    return genericMsg(
      'Welcome to <span class="highlight">GTAMarathon 2024</span>! Enjoy the show!'
    );
  }

  function merchPromo() {
    return genericMsg(
      'Check out the merch store over at <span class="highlight">store.streamelements.com/gtamarathon</span>!'
    );
  }
  function schedulePromo() {
    return genericMsg(
      `Type <span class="highlight">!schedule</span> in the chat to see what's on next!`
    );
  }

  function nextRun() {
    return {
      name: NextRun,
    };
  }
</script>

// src/browser/graphics/components/omnibar/Ticker.tsx
import type { DonationGoal } from '@gtam-layouts/types/custom/Tiltify-Types'
import type { CSSProperties } from 'react'
import { useEffect, useRef, useState } from 'react'
import { CSSTransition, SwitchTransition } from 'react-transition-group'
import { NextMilestone } from './Ticker//NextMilestone'
import { GenericMessage } from './Ticker/GenericMessage'
import { NextRun } from './Ticker/NextRun'

export function Ticker({ style }: { style: CSSProperties }) {
  const currentComponentIndex = useRef(0)
  const currentComponentContainer = useRef<HTMLSpanElement | null>(null)
  const [timestamp, setTimestamp] = useState(Date.now())
  const [messageTypes, setMessageTypes] = useState<React.JSX.Element[]>([])
  const [currentElement, setCurrentElement] = useState<React.JSX.Element | undefined>()
  const messageTypesRef = useRef<React.JSX.Element[]>([])
  const [hasActiveGoals, setHasActiveGoals] = useState(false)
  const donationTotal = nodecg.Replicant<number>('donationTotal')
  const donationGoals = nodecg.Replicant<DonationGoal[]>('donationGoals')

  useEffect(() => {
    NodeCG.waitForReplicants(donationGoals).then(() => {
      const handler = (goals: DonationGoal[] = []) => {
        const activeGoals = goals.some(goal => (donationTotal.value ?? 0) < goal.amount)
        setHasActiveGoals(activeGoals)
      }
      donationGoals.on('change', handler)
      return () => donationGoals.removeListener('change', handler)
    })
  }, [donationGoals, donationTotal.value])

  useEffect(() => {
    const newMessages = [
      genericMessage('welcome', 'Welcome to <span class="highlight">GTAMarathon 2025</span>! Enjoy the show!'),
      genericMessage('merch', 'Check out the merch store over at <span class="highlight">merch.gtamarathon.com</span>!'),
      genericMessage('schedule', `Type <span class="highlight">!schedule</span> in the chat to see what's on next!`),
      <NextRun key="next-run" time={20} onEnd={showNextElement} />,
      ...(hasActiveGoals ? [<NextMilestone key="next-milestone" time={20} onEnd={showNextElement} />] : []),
    ]

    setMessageTypes(newMessages)
    messageTypesRef.current = newMessages
    setCurrentElement(newMessages[0])

    function genericMessage(key: string, message: string) {
      return <GenericMessage key={key} message={message} time={20} onEnd={showNextElement} />
    }
  }, [hasActiveGoals])

  useEffect(() => {
    currentComponentIndex.current = 0
  }, [messageTypes])

  function showNextElement() {
    console.log('Showing next omnibar message')

    currentComponentIndex.current = (currentComponentIndex.current + 1) % messageTypesRef.current.length
    const nextElement = messageTypesRef.current[currentComponentIndex.current]

    setTimestamp(Date.now())
    setCurrentElement(nextElement)
  }

  return (
    <div
      id="Ticker"
      style={{
        overflow: 'hidden',
        flex: '0 0 auto',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        ...style,
      }}
    >
      <SwitchTransition mode="out-in">
        <CSSTransition
          key={currentElement?.key || 'fallback'}
          nodeRef={currentComponentContainer}
          in={!!currentElement}
          appear
          timeout={1000}
          classNames={{
            enter: 'animate__animated animate__slideInUp',
            exit: 'animate__animated animate__slideOutUp',
          }}
        >
          <span key={timestamp} ref={currentComponentContainer}>
            {currentElement ?? <span />}
          </span>
        </CSSTransition>
      </SwitchTransition>

    </div>
  )
}
