// src/graphics/game-layout/components/MediaBox/TwitchSub.vue
<template>
  <div
    id="MediaBoxTwitchSub"
    v-if="data && data.subInfo"
    :style="{
      textShadow: '2px 2px 2px #12222c',
      flexDirection: 'column',
      gap: '20px',
    }"
    class="Flex"
  >
    <img :src="getRandomEmote()" />
    <span :style="{ fontWeight: 'normal' }"
      ><b class="highlight">{{ data.subInfo.name }}</b> has subscribed with a
      <b class="highlight">Tier {{ data.subInfo.tier }}</b> subscription for
      <b class="highlight">{{ data.subInfo.months }} months</b>!</span
    >
  </div>
</template>

<script setup lang="ts">
  import type { SubQueueItem } from '@gtam-layouts/types';
  import { defineProps, defineEmits, onMounted } from 'vue';
  import { getRandomEmote } from './randomEmote';
  const props = defineProps<{ data: { subInfo: SubQueueItem | undefined } }>();
  const emit = defineEmits(['end']);

  onMounted(() => {
    setTimeout(() => {
      emit('end');
    }, 25000);
  });
</script>

<style scoped>
  .highlight {
    color: #4fbafe;
  }
</style>

// src/browser/graphics/components/game-layouts/components/MediaBox/TwitchSub.tsx
import type { SubQueueItem } from '@gtam-layouts/types'
import { getRandomEmote } from './randomEmote'

interface Props {
  subInfo: SubQueueItem
}

export function MediaBoxTwitchSub({ subInfo }: Props) {
  const { name, tier, months } = subInfo

  return (
    <>
      {name && tier && months && (
        <div
          id="MediaBoxTwitchSub"
          style={{
            textShadow: '2px 2px 2px #12222c',
            flexDirection: 'column',
            gap: '20px',
          }}
          className="Flex"
        >
          <img src={getRandomEmote()} />
          <span style={{ fontWeight: 'normal' }}>
            <b style={{ color: '#4fbafe' }}>{name}</b>
            has subscribed
            <b style={{ color: '#4fbafe' }}>
              Tier
              {tier}
            </b>
            subscription for
            <b style={{ color: '#4fbafe' }}>
              {months}
              months
            </b>
            !
          </span>
        </div>
      )}
    </>
  )
}
